-- Schema for the aigents vector store.
--
-- Runs once, from the pgvector image's /docker-entrypoint-initdb.d hook, when the
-- data directory is still empty. ${embedding_dimensions} matches the hidden size
-- of the Qwen3 embedding space, so vectors produced by the model container drop
-- straight into these tables.

CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------- documents
-- One row per embedded document. content is the raw text handed to the model,
-- metadata carries whatever the caller wants to filter on.
CREATE TABLE IF NOT EXISTS documents (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection  TEXT        NOT NULL DEFAULT 'default',
  source      TEXT,
  content     TEXT        NOT NULL,
  metadata    JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS documents_collection_idx ON documents (collection);

-- ---------------------------------------------------------------- embeddings
-- Vectors live in their own table so an ANN index can be rebuilt without
-- touching the document rows.
CREATE TABLE IF NOT EXISTS document_embeddings (
  document_id BIGINT PRIMARY KEY REFERENCES documents (id) ON DELETE CASCADE,
  model       TEXT        NOT NULL,
  dimensions  INTEGER     NOT NULL,
  embedding   vector(${embedding_dimensions}) NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS document_embeddings_model_idx
  ON document_embeddings (model);

-- ------------------------------------------------------------------ search
-- Cosine distance lookup. This is an exact scan; pgvector handles the ORDER BY
-- just fine until the table grows, at which point add an ANN index (IVFFlat
-- needs rows to exist first, HNSW does not, hence why neither is created here):
--
--   CREATE INDEX document_embeddings_ivfflat
--     ON document_embeddings USING ivfflat (embedding vector_cosine_ops)
--     WITH (lists = 200);
--
--   CREATE INDEX document_embeddings_hnsw
--     ON document_embeddings USING hnsw (embedding vector_cosine_ops);
CREATE OR REPLACE FUNCTION match_documents(
  query_embedding     vector(${embedding_dimensions}),
  match_count         INTEGER DEFAULT 8,
  filter_collection   TEXT    DEFAULT NULL,
  filter_metadata     JSONB   DEFAULT NULL
)
RETURNS TABLE (
  document_id BIGINT,
  content     TEXT,
  metadata    JSONB,
  distance    DOUBLE PRECISION
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    e.document_id,
    d.content,
    d.metadata,
    e.embedding <=> query_embedding AS distance
  FROM document_embeddings e
  JOIN documents d ON d.id = e.document_id
  WHERE (filter_collection IS NULL OR d.collection = filter_collection)
    AND (filter_metadata IS NULL OR d.metadata @> filter_metadata)
  ORDER BY e.embedding <=> query_embedding
  LIMIT match_count;
$$;